FROM peract-miso-base

# -------- RLBench (PerAct fork) --------
WORKDIR /root
RUN git clone -b peract https://github.com/MohitShridhar/RLBench.git
WORKDIR /root/RLBench
RUN /opt/conda/envs/peract-miso/bin/pip install -e .

# -------- YARR (PerAct fork) --------
WORKDIR /root
RUN git clone -b peract https://github.com/MohitShridhar/YARR.git
WORKDIR /root/YARR
# Only pip<24.1 works with hydra-core==1.0.5 and omegaconf==2.0.5
RUN /opt/conda/envs/peract-miso/bin/pip install "pip<24.1" && \
    /opt/conda/envs/peract-miso/bin/pip install \
    tensorboard \
    moviepy \
    natsort \
    psutil \
    timeout-decorator \
    pyrender==0.1.45 \
    omegaconf==2.0.5 \
    hydra-core==1.0.5 \
    pandas==1.4.1 \
    opencv-python

RUN /opt/conda/envs/peract-miso/bin/python setup.py develop --no-deps

# -------- ARM --------
WORKDIR /root
RUN git clone https://github.com/stepjam/ARM.git /root/ARM \
    && /opt/conda/envs/peract-miso/bin/pip install -r /root/ARM/requirements.txt

ENV PYTHONPATH="/root/ARM:${PYTHONPATH}"
ENV PYOPENGL_PLATFORM=egl

# -------- PerAct --------
WORKDIR /root
RUN git clone https://github.com/peract/peract.git
WORKDIR /root/peract

# Downgrade setuptools to avoid strip_trailing_zero bug
RUN /opt/conda/envs/peract-miso/bin/pip install "setuptools<70"

RUN /opt/conda/envs/peract-miso/bin/pip install git+https://github.com/openai/CLIP.git && \
    /opt/conda/envs/peract-miso/bin/pip install \
    absl-py==0.15.0 \
    einops==0.3.2 \
    ftfy \
    gdown==3.13.1 \
    hydra-core==1.0.5 \
    matplotlib \
    numpy==1.21 \
    packaging==21.3 \
    pandas==1.4.1 \
    pyrender==0.1.45 \
    regex \
    scipy==1.7.3 \
    tensorboard \
    transformers==4.3.2 \
    trimesh==3.9.34

ENV PERACT_ROOT=/root/peract
RUN /opt/conda/envs/peract-miso/bin/pip install -e . --no-deps
ENV PYTHONPATH="/root:${PYTHONPATH}"

# Patch pyrender to remove Viewer import (headless fix)
RUN sed -i '/from \.viewer import Viewer/d' /opt/conda/envs/peract-miso/lib/python3.9/site-packages/pyrender/__init__.py && \
    sed -i "s/'Viewer',//" /opt/conda/envs/peract-miso/lib/python3.9/site-packages/pyrender/__init__.py && \
    rm -rf /opt/conda/envs/peract-miso/lib/python3.9/site-packages/pyrender/__pycache__

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libegl1 \
    libgles2-mesa-dev \
    libosmesa6-dev \
    libglu1-mesa \
    && rm -rf /var/lib/apt/lists/*


# -------- Environment --------
ENV PYOPENGL_PLATFORM=egl
ENV WORLD_SIZE=1
ENV RANK=0

# -------- Auto-activate peract-miso env on shell startup --------
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/conda/bin/activate peract-miso" >> ~/.bashrc

WORKDIR /workspace
