name: peract-miso
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.3.0
    - addict==2.4.0
    - argcomplete==3.6.2
    - asttokens==3.0.0
    - attrs==25.3.0
    - blinker==1.9.0
    - cachetools==5.5.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.2
    - configargparse==1.7.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - dash==3.0.4
    - dearpygui==2.0.0
    - decorator==5.2.1
    - evo==1.31.1
    - exceptiongroup==1.3.0
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - flask==3.0.3
    - fonttools==4.58.2
    - google-auth==2.40.3
    - google-auth-oauthlib==1.0.0
    - grpcio==1.72.1
    - idna==3.10
    - imageio==2.37.0
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - iopath==0.1.10
    - ipython==8.18.1
    - ipywidgets==8.1.7
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.1
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter-core==5.8.1
    - jupyterlab-widgets==3.0.15
    - kiwisolver==1.4.7
    - lpips==0.1.4
    - lz4==4.4.4
    - markdown==3.8
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - narwhals==1.41.1
    - natsort==8.4.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - ninja==1.11.1.4
    - numexpr==2.10.2
    - numpy>=1.23,<1.25
    - oauthlib==3.2.2
    - open3d==0.19.0
    - opencv-python==4.11.0.86
    - packaging==25.0
    - pandas==2.3.0
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.2.1
    - platformdirs==4.3.8
    - plotly==6.1.2
    - portalocker==3.1.1
    - prompt-toolkit==3.0.51
    - protobuf==6.31.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pygments==2.19.1
    - pymcubes==0.1.6
    - pyparsing==3.2.3
    - pyquaternion==0.9.9
    - pysdf==0.1.9
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - referencing==0.36.2
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - retrying==1.3.4
    - rich==14.0.0
    - rosbags==0.9.23
    - rpds-py==0.25.1
    - rsa==4.9.1
    - ruamel-yaml==0.18.13
    - ruamel-yaml-clib==0.2.12
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - six==1.17.0
    - stack-data==0.6.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.6.0
    - torch-ema==0.3
    - tqdm==4.67.1
    - traitlets==5.14.3
    - trimesh==4.6.11
    - typing-extensions==4.14.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - wcwidth==0.2.13
    - werkzeug==3.0.6
    - widgetsnbextension==4.0.14
    - zipp==3.22.0
    - zstandard==0.23.0
